CompileFlags:
  Compiler: /opt/homebrew/bin/g++-13
  Add:
    - -std=gnu++20
    - -I/opt/homebrew/include
    - -I/opt/homebrew/Cellar/gcc/13.2.0/include/c++/13
    - -I/opt/homebrew/Cellar/gcc/13.2.0/include/c++/13/aarch64-apple-darwin23
  Remove:
    - -W*

Diagnostics:
  Suppress:
    - pp_file_not_found
